/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.model.User;

public class App {
    public static void main(String[] args) {
        User john = new User("John", 30);

//        User john = UserBuilder.builder()
//                .name("John")
//                .age(30)
//                .build();

        System.out.println("name: " + john.getName());

    }
}
